[package]
name = "web_scrapper_in_rust"
version = "0.1.0"
edition = "2022"

[dependencies]
# HTTP and Web Scrapper
reqwest = "0.9.5"
scraper = "0.9.0"
select = "0.4.2"

# table form print
prettytable-rs = "^0.8"
